### ISSUE TITLE
UsIng Different Visualizers

### ISSUE THREAD

**Issue by konrad51** [CaiB/ColorChord.NET#21]
I'm back again ! Not really an issue, but how would I go about using a different visualizer ( Voronoi or cells for example) ? I'm using SampleLinear....it was already in config.json. Thanks

**Comment by CaiB** [comment]
CC.NET supports any number of visualizers and outputs running at once. So you can have your light bulbs use one visualizer, and the on-screen display use another if you'd like. Or you can use the same for both.

To add a visualizer, simply look through the list on the website, and pick one you like (e.g. [Voronoi](http://www.colorchord.net/docs/visualizers/voronoi/)). Near the top of the page, it will show what output modes it supports (for Voronoi, `Discrete 2D`). To use 2 or more visualizers at once, you can just add a new entry to the Visualizers list in the config.json. For example:
```json
"Visualizers":
[
    {
        "Type": "Linear",
        "Name": "SampleLinear",
        "LEDCount": 720,
        ...
    },
    {
        "Type": "Voronoi",
        "Name": "MyVoronoi",
        // Add any other desired config options here
     }
]
```
Then, you can look through the website again to find which outputs you'd like to use. At the top of each one, it will list the input modes it supports. The visualizer and output must have at least 1 in common for them to work together.  
For Voronoi, because it generates `Discrete 2D` data, the only output that currently supports that is [DisplayOpenGL->BlockMatrix](http://www.colorchord.net/docs/outputs/displayopengl/#blockmatrix).

Currently, you can only have 1 instance of DisplayOpenGL (but as many other outputs as you like). So to use Voronoi, you can change the existing DisplayOpenGL like so:
```json
"Outputs":
[
    {
        "Type": "DisplayOpenGL",
        "Name": "SampleDisplay",
        "VisualizerName": "MyVoronoi", // Connects to the Voronoi visualizer
        "Modes":
        [
            {
                "Type": "BlockMatrix"
                // Many modes will have additional config options you can put here
            }
        ],
        "WindowWidth": 640,
        "WindowHeight": 480
    }
]
```

Note that the `"VisualizerName"` in the DisplayOpenGL Output is matched to the `"Name"` of the visualizer, this is how CC.NET knows how to pipe data between them.

For Cells, it outputs `Discrete 1D` data, so there are quite a few options for outputs that can use its data.

Hopefully that makes sense, let me know if you have any further questions!

**Comment by CaiB** [comment]
Did this answer your questions? I'll close the issue if so. Otherwise, feel free to let me know if there's anything that's still unclear.

**Comment by konrad51** [comment]
Yes, it did. Thank you very much!
