### ISSUE TITLE
Parameter names for note finder not matching in config

### ISSUE THREAD

**Issue by 0xD34DC0DE** [CaiB/ColorChord.NET#9]
In the documentation the names for the notefinder's parameter aren't consistent with the names required by the configuration file to be applied

(Mostly capitalisation of the first letter)

![Screenshot_229](https://user-images.githubusercontent.com/31230799/115464342-ede47380-a1fa-11eb-934d-b83b37570ea8.png)

![Screenshot_228](https://user-images.githubusercontent.com/31230799/115464278-d1e0d200-a1fa-11eb-938b-34b91818c1e9.png)

**Comment by CaiB** [comment]
I'm assuming you're using the latest release version v0.5? At this point it's pretty old and config options have changed quite a bit since then. The website has only documentation for the new format, apologies for the confusion.

I'll try to get v0.6 out soon, there's just one feature I still want to finish up before calling it ready.

**Comment by 0xD34DC0DE** [comment]
yes it is the 0.5 release

**Comment by CaiB** [comment]
I've released v0.6 as "stable", which uses the new config names. Now the website and "stable" release line up once again, so I'll close this.
